how to set seed: https://www.tensorflow.org/api_docs/python/tf/random/set_seed

In [1]:
import tensorflow as tf

In [2]:
# set global seed, generate data from uniform distribution
# Calling tf.random.set_seed will reset

tf.random.set_seed(41)
a1 = tf.random.uniform([3, 4])
a2 = tf.random.uniform([3, 4])
tf.random.set_seed(41)
b1 = tf.random.uniform([3, 4])
b2= tf.random.uniform([3, 4])

a1 == b1, a2 == b2

(<tf.Tensor: id=29, shape=(3, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])>,
 <tf.Tensor: id=30, shape=(3, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])>)

In [38]:
# set operation seed
tf.random.uniform([3, 4], seed=1)

<tf.Tensor: id=539, shape=(3, 4), dtype=float32, numpy=
array([[0.99904716, 0.14571881, 0.44707942, 0.98799264],
       [0.34303963, 0.9633211 , 0.82642746, 0.05665267],
       [0.10475743, 0.22526276, 0.19121397, 0.13528359]], dtype=float32)>

In [39]:
tf.random.uniform([3, 4], seed=1)

<tf.Tensor: id=546, shape=(3, 4), dtype=float32, numpy=
array([[0.02549303, 0.04059029, 0.27095473, 0.3669634 ],
       [0.06870067, 0.50469637, 0.70100105, 0.97114563],
       [0.335554  , 0.2977351 , 0.8496797 , 0.63130164]], dtype=float32)>

In [34]:
# @tf.function is like to re-run the program
@tf.function
def f():
    a = tf.random.uniform([3, 4], seed=1)
    b = tf.random.uniform([3, 4], seed=1)
    return a,b

@tf.function
def g():
    a = tf.random.uniform([3, 4], seed=1)
    b = tf.random.uniform([3, 4], seed=1)
    return a,b

a1, b1 = f()
a2, b2 = g()

a1 == a2, b1 == b2

(<tf.Tensor: id=510, shape=(3, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])>,
 <tf.Tensor: id=511, shape=(3, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])>)

In [3]:
# if interrupt the kernel and run again, it will be reset
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.2390374], shape=(1,), dtype=float32)
tf.Tensor([0.22267115], shape=(1,), dtype=float32)


In [2]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.2390374], shape=(1,), dtype=float32)
tf.Tensor([0.22267115], shape=(1,), dtype=float32)


In [7]:
# 
@tf.function
def foo():
    a = tf.random.uniform([1], seed=1)
    b = tf.random.uniform([1], seed=1)
    return a,b

print(foo())  # prints '(A1, A1)'
print(foo())  # prints '(A2, A2)'

(<tf.Tensor: id=126, shape=(1,), dtype=float32, numpy=array([0.2390374], dtype=float32)>, <tf.Tensor: id=127, shape=(1,), dtype=float32, numpy=array([0.2390374], dtype=float32)>)
(<tf.Tensor: id=128, shape=(1,), dtype=float32, numpy=array([0.22267115], dtype=float32)>, <tf.Tensor: id=129, shape=(1,), dtype=float32, numpy=array([0.22267115], dtype=float32)>)


In [6]:
@tf.function
def bar():
    a = tf.random.uniform([1])
    b = tf.random.uniform([1])
    return a,b
print(bar())  # prints '(A1, A2)'
print(bar())  # prints '(A3, A4)'

(<tf.Tensor: id=103, shape=(1,), dtype=float32, numpy=array([0.16628528], dtype=float32)>, <tf.Tensor: id=104, shape=(1,), dtype=float32, numpy=array([0.34695327], dtype=float32)>)
(<tf.Tensor: id=105, shape=(1,), dtype=float32, numpy=array([0.7221612], dtype=float32)>, <tf.Tensor: id=106, shape=(1,), dtype=float32, numpy=array([0.23924577], dtype=float32)>)


In [11]:
@tf.function
def f():
    a = tf.random.stateless_uniform([1], seed=(2, 3))
    b = tf.random.stateless_uniform([1], seed=(2, 3))
    return a,b
print(f())
print(f())

(<tf.Tensor: id=182, shape=(1,), dtype=float32, numpy=array([0.17481351], dtype=float32)>, <tf.Tensor: id=183, shape=(1,), dtype=float32, numpy=array([0.17481351], dtype=float32)>)
(<tf.Tensor: id=184, shape=(1,), dtype=float32, numpy=array([0.17481351], dtype=float32)>, <tf.Tensor: id=185, shape=(1,), dtype=float32, numpy=array([0.17481351], dtype=float32)>)
