In [1]:
import tensorflow as tf

In [2]:
tensor = tf.random.uniform([2, 3, 4, 5])
tensor

<tf.Tensor: id=6, shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0.5946728 , 0.8504107 , 0.9453808 , 0.01669943, 0.04965234],
         [0.6505476 , 0.53596425, 0.78144205, 0.30099106, 0.83391106],
         [0.77749133, 0.05834424, 0.40906346, 0.20359933, 0.28881943],
         [0.9422455 , 0.9662969 , 0.7776294 , 0.40017235, 0.29348767]],

        [[0.14954448, 0.8318533 , 0.4006511 , 0.5567336 , 0.83203435],
         [0.9396932 , 0.43192422, 0.11512089, 0.66050386, 0.30559158],
         [0.48491788, 0.5460279 , 0.9194999 , 0.52830136, 0.5340731 ],
         [0.10136437, 0.9935181 , 0.08195198, 0.9520602 , 0.8299929 ]],

        [[0.8451494 , 0.87296295, 0.9285543 , 0.78857994, 0.28002155],
         [0.8151357 , 0.2294271 , 0.31927812, 0.6540221 , 0.6555997 ],
         [0.96309435, 0.57878625, 0.4100287 , 0.11370695, 0.10104668],
         [0.4678898 , 0.8936585 , 0.3297739 , 0.9712597 , 0.15244079]]],


       [[[0.4385209 , 0.7455094 , 0.6993866 , 0.15616739, 0.3329463 ],
         

In [3]:
# take the first 2 elements from every dim
tensor[:2, :2, :2, :2]

<tf.Tensor: id=10, shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0.5946728 , 0.8504107 ],
         [0.6505476 , 0.53596425]],

        [[0.14954448, 0.8318533 ],
         [0.9396932 , 0.43192422]]],


       [[[0.4385209 , 0.7455094 ],
         [0.15965605, 0.14349508]],

        [[0.49562705, 0.6698359 ],
         [0.55839217, 0.06848252]]]], dtype=float32)>

In [4]:
# get the first element from every dim except the last one
tensor[:1, :1, :1]

<tf.Tensor: id=14, shape=(1, 1, 1, 5), dtype=float32, numpy=
array([[[[0.5946728 , 0.8504107 , 0.9453808 , 0.01669943, 0.04965234]]]],
      dtype=float32)>

In [7]:
# add extra dimentions
rank_2_tensor = tf.constant([[2, 3],
                             [1, 4]])

In [9]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # the same as [:, :, tf.newaxis]
rank_3_tensor

<tf.Tensor: id=28, shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[1],
        [4]]], dtype=int32)>

In [10]:
rank_4_tensor = rank_3_tensor[..., tf.newaxis]
rank_4_tensor

<tf.Tensor: id=32, shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[2]],

        [[3]]],


       [[[1]],

        [[4]]]], dtype=int32)>

In [12]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # expand the last axis

<tf.Tensor: id=34, shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[1],
        [4]]], dtype=int32)>

In [14]:
tf.expand_dims(rank_2_tensor, axis=0) # expand the first axis

<tf.Tensor: id=38, shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 3],
        [1, 4]]], dtype=int32)>

In [15]:
# the expanded tensor should be stored in another variable
rank_2_tensor

<tf.Tensor: id=20, shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [1, 4]], dtype=int32)>