In [1]:
import tensorflow as tf

In [11]:
# tf.random.set_seed(34)
not_shuffled = tf.random.uniform([5, 3])
print(not_shuffled)

tf.Tensor(
[[0.52854156 0.42819154 0.45035434]
 [0.9802803  0.68966055 0.02345836]
 [0.42223263 0.82452154 0.5857358 ]
 [0.776384   0.26451886 0.7128879 ]
 [0.33855987 0.51591027 0.65031374]], shape=(5, 3), dtype=float32)


### Without seed: the shuffle result will be differente at each time. 

In [14]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: id=22, shape=(5, 3), dtype=float32, numpy=
array([[0.42223263, 0.82452154, 0.5857358 ],
       [0.52854156, 0.42819154, 0.45035434],
       [0.776384  , 0.26451886, 0.7128879 ],
       [0.9802803 , 0.68966055, 0.02345836],
       [0.33855987, 0.51591027, 0.65031374]], dtype=float32)>

In [15]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: id=23, shape=(5, 3), dtype=float32, numpy=
array([[0.776384  , 0.26451886, 0.7128879 ],
       [0.52854156, 0.42819154, 0.45035434],
       [0.33855987, 0.51591027, 0.65031374],
       [0.42223263, 0.82452154, 0.5857358 ],
       [0.9802803 , 0.68966055, 0.02345836]], dtype=float32)>

In [16]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: id=24, shape=(5, 3), dtype=float32, numpy=
array([[0.776384  , 0.26451886, 0.7128879 ],
       [0.9802803 , 0.68966055, 0.02345836],
       [0.52854156, 0.42819154, 0.45035434],
       [0.42223263, 0.82452154, 0.5857358 ],
       [0.33855987, 0.51591027, 0.65031374]], dtype=float32)>

### With seed: the shuffle result will be the same at each time.

The global seed and the operation seed should both be set as the same for every time.

In [33]:
tf.random.set_seed(41)
tf.random.shuffle(not_shuffled, seed=2)

<tf.Tensor: id=38, shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [34]:
tf.random.set_seed(41)
tf.random.shuffle(not_shuffled, seed=2)

<tf.Tensor: id=39, shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>